# Generated by Django 4.2.7 on 2024-12-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_groups_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='can_add_materials',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_add_notes',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_assist_employees',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_confirm_status',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_create_task',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_delete_task',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_delete_user',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_edit_task',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_edit_user',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_execute_task',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_view_reports',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='can_view_task',
        ),
        migrations.AddField(
            model_name='usertype',
            name='is_empolyee',
            field=models.BooleanField(default=False),
        ),
    ]
