# Generated by Django 4.2.7 on 2024-12-05 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_usertype_can_add_materials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'permissions': [('can_assign_task', 'Can assign tasks to users')]},
        ),
        migrations.RemoveField(
            model_name='task',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='materials_required',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.AddField(
            model_name='taskaction',
            name='materials_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
